feat(pencil): add  option

diff --git a/.github/workflows/release.yaml b/.github/workflows/release.yaml
--- a/.github/workflows/release.yaml
+++ b/.github/workflows/release.yaml
@@ -95,17 +95,26 @@ jobs:
     - name: Run semantic release
       id: semantic_release
       run: |
-          version=$(npx semantic-release --dry-run | grep -oP "(?<=The next release version is )\S+")
-          if [ -z "$version" ]; then
-            echo "Error: Could not extract release version."
-            exit 1
-          fi
-          echo "Extracted version: $version"
-          echo "new_release=$version" >> $GITHUB_ENV
-          echo "::set-output name=version::$version"  # Esto guarda la versión como salida del job
+       export VERSION=$(npx semantic-release --dry-run | grep 'The next release version is' | sed -E 's/.* ([[:digit:].]+)$/\1/')
+       if [ -z "$VERSION" ]; then
+        echo "Failed to determine version" >&2
+        exit 1
+       fi
+       echo "version=${VERSION}-${GITHUB_SHA::12}" >> $GITHUB_OUTPUT
+
 
       env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+
+    - name: Perform release
+      id: perform_release
+      env:
+        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+      run: npx semantic-release
+
+    - name: view generated version
+      run: echo "version=${{ steps.semantic_release.outputs.version }}"
+  
 
   deploy:
    runs-on: ubuntu-latest
