feat(pencil): add  option

diff --git a/.github/workflows/release.yaml b/.github/workflows/release.yaml
--- a/.github/workflows/release.yaml
+++ b/.github/workflows/release.yaml
@@ -73,73 +73,72 @@ jobs:
             -Dsonar.qualitygate.wait=true \
 
   release:
-    name: Semantic Release
-    runs-on: ubuntu-latest
-    needs: static-code-analysis
+   name: Semantic Release
+   runs-on: ubuntu-latest
+   needs: static-code-analysis
 
-    steps:
-      - name: Checkout code
-        uses: actions/checkout@v4
+   steps:
+    - name: Checkout code
+      uses: actions/checkout@v4
 
-      - name: Set up Node.js
-        uses: actions/setup-node@v4
-        with:
-          node-version: '20.x'
+    - name: Set up Node.js
+      uses: actions/setup-node@v4
+      with:
+        node-version: '20.x'
 
-      - name: Install dependencies
-        run: npm ci
-      
-      - name: Debug Semantic Release Output
-        run: npx semantic-release --dry-run
-      
-      - name: Run semantic release
-        id: set_version
-        run: |
-            version=$(npx semantic-release --dry-run | grep -oP "(?<=The next release version is )\S+")
-            if [ -z "$version" ]; then
-              echo "Error: Could not extract release version."
-              exit 1
-            fi
-            echo "new_release=$version" >> $GITHUB_ENV
-
-        env:
-          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-
+    - name: Install dependencies
+      run: npm ci
     
+    - name: Debug Semantic Release Output
+      run: npx semantic-release --dry-run
+    
+    - name: Run semantic release
+      id: semantic_release
+      run: |
+          version=$(npx semantic-release --dry-run | grep -oP "(?<=The next release version is )\S+")
+          if [ -z "$version" ]; then
+            echo "Error: Could not extract release version."
+            exit 1
+          fi
+          echo "new_release=$version" >> $GITHUB_ENV
+          echo "::set-output name=version::$version"  # Esto guarda la versión como salida del job
+
+      env:
+        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
 
   deploy:
-    runs-on: ubuntu-latest
-    needs: release
+   runs-on: ubuntu-latest
+   needs: release
 
-    permissions:
-      contents: read
-      id-token: write
+   permissions:
+    contents: read
+    id-token: write
 
-    steps:
-      - name: Checkout code
-        uses: actions/checkout@v4
+   steps:
+    - name: Checkout code
+      uses: actions/checkout@v4
 
-      - name: Authenticate to Google Cloud
-        uses: google-github-actions/auth@v2
-        with:
-          workload_identity_provider: '${{ env.WORKLOAD_IDENTITY_PROVIDER }}'
-          service_account: '${{ env.SERVICE_ACCOUNT }}'
+    - name: Authenticate to Google Cloud
+      uses: google-github-actions/auth@v2
+      with:
+        workload_identity_provider: '${{ env.WORKLOAD_IDENTITY_PROVIDER }}'
+        service_account: '${{ env.SERVICE_ACCOUNT }}'
 
-      - name: Configure Docker for Artifact Registry
-        run: gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev
+    - name: Configure Docker for Artifact Registry
+      run: gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev
 
-      - name: Build and Push cocohomes Backend Image
-        uses: docker/build-push-action@v6
-        with:
-          context: .
-          push: true
-          tags: '${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/cloud-run-source-deploy/${{ env.SERVICE }}:${{ needs.semantic_release.outputs.version }}'
+    - name: Build and Push cocohomes Backend Image
+      uses: docker/build-push-action@v6
+      with:
+        context: .
+        push: true
+        tags: '${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/cloud-run-source-deploy/${{ env.SERVICE }}:${{ needs.release.outputs.version }}'  # Usamos la salida `version`
 
-      - name: Deploy Backend to Cloud Run
-        uses: google-github-actions/deploy-cloudrun@v2
-        with:
-          service: '${{ env.SERVICE }}'
-          region: '${{ env.REGION }}'
-          image: '${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/cloud-run-source-deploy/${{ env.SERVICE }}:${{  needs.semantic_release.outputs.version }}'
-          env_vars: |
-            ENVIRONMENT=pro
+    - name: Deploy Backend to Cloud Run
+      uses: google-github-actions/deploy-cloudrun@v2
+      with:
+        service: '${{ env.SERVICE }}'
+        region: '${{ env.REGION }}'
+        image: '${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/cloud-run-source-deploy/${{ env.SERVICE }}:${{ needs.release.outputs.version }}'  # Usamos la salida `version`
+        env_vars: |
+          ENVIRONMENT=prod
