feat(pencil): add 'graphiteWidth' option

diff --git a/.github/workflows/release.yaml b/.github/workflows/release.yaml
--- a/.github/workflows/release.yaml
+++ b/.github/workflows/release.yaml
@@ -92,8 +92,12 @@ jobs:
       - name: Run semantic release
         id: set_version
         run: |
-          version=$(npx semantic-release --dry-run | grep 'The next release version is' | awk '{print $NF}')
-          echo "::set-output name=version::$version"
+            version=$(npx semantic-release --dry-run | grep -oP "(?<=The next release version is )\S+")
+            if [ -z "$version" ]; then
+              echo "Error: Could not extract release version."
+              exit 1
+            fi
+            echo "new_release=$version" >> $GITHUB_ENV
 
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
